version: "2"
services:

  mariadb:
    image: linuxserver/mariadb
    container_name: mariadb
    environment:
      - PUID=1001 #trocar pelo id do usuario
      - PGID=1001 #trocar pelo id do grupo de usuario
      - MYSQL_ROOT_PASSWORD=mariadbpassword
      - TZ=Europe/Berlin
      - MYSQL_DATABASE=WP_database
      - MYSQL_USER=WP_dbuser
      - MYSQL_PASSWORD=WP_dbpassword
    volumes:
      - /opt/backend_swag/config/mariadb:/config
    restart: unless-stopped

  swag:
    image: linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1001 #trocar pelo id do usuario
      - PGID=1001 #trocar pelo id do grupo de usuario
      - TZ=America/Sao_Paulo
      - URL=exemplo.com
      - SUBDOMAINS=www
      - VALIDATION=http
    volumes:
      - /opt/backend_swag/config:/config
    ports:
      - 443:443
      - 80:80 #optional
    depends_on:
      - mariadb
    restart: unless-stopped
